version: "3.8"

services:
  postgres:
    image: paradedb/paradedb:latest
    ports:
      - 5450:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
    volumes:
      - ./data/pg:/data/postgres

  cache:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - 6380:6379
    volumes:
      - ./data/kv:/data/dragonfly
  
  tracing:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.9.0
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"
    restart: "no"
