/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  CreatePromotionControllerHandle400,
  CreatePromotionControllerHandle401,
  CreatePromotionControllerHandle404,
  CreatePromotionControllerHandle409,
  CreatePromotionControllerHandle500,
  CreatePromotionControllerHandleMutationRequest,
  CreatePromotionControllerHandleMutationResponse,
} from "../types/CreatePromotionControllerHandle.ts";

function getCreatePromotionControllerHandleUrl() {
  const res = { method: "POST", url: `/promotions` as const };
  return res;
}

/**
 * @summary Create a promotion
 * {@link /promotions}
 */
export async function createPromotionControllerHandle(
  data: CreatePromotionControllerHandleMutationRequest,
  config: Partial<
    RequestConfig<CreatePromotionControllerHandleMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const res = await request<
    CreatePromotionControllerHandleMutationResponse,
    ResponseErrorConfig<
      | CreatePromotionControllerHandle400
      | CreatePromotionControllerHandle401
      | CreatePromotionControllerHandle404
      | CreatePromotionControllerHandle409
      | CreatePromotionControllerHandle500
    >,
    CreatePromotionControllerHandleMutationRequest
  >({
    method: "POST",
    url: getCreatePromotionControllerHandleUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res;
}
