/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  CreateCouponControllerHandle400,
  CreateCouponControllerHandle401,
  CreateCouponControllerHandle404,
  CreateCouponControllerHandle409,
  CreateCouponControllerHandle500,
  CreateCouponControllerHandleMutationRequest,
  CreateCouponControllerHandleMutationResponse,
} from "../types/CreateCouponControllerHandle.ts";

function getCreateCouponControllerHandleUrl() {
  const res = { method: "POST", url: `/coupons` as const };
  return res;
}

/**
 * @summary Create a coupon
 * {@link /coupons}
 */
export async function createCouponControllerHandle(
  data: CreateCouponControllerHandleMutationRequest,
  config: Partial<
    RequestConfig<CreateCouponControllerHandleMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const res = await request<
    CreateCouponControllerHandleMutationResponse,
    ResponseErrorConfig<
      | CreateCouponControllerHandle400
      | CreateCouponControllerHandle401
      | CreateCouponControllerHandle404
      | CreateCouponControllerHandle409
      | CreateCouponControllerHandle500
    >,
    CreateCouponControllerHandleMutationRequest
  >({
    method: "POST",
    url: getCreateCouponControllerHandleUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res;
}
