/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  CreateUserCouponControllerHandle400,
  CreateUserCouponControllerHandle401,
  CreateUserCouponControllerHandle404,
  CreateUserCouponControllerHandle409,
  CreateUserCouponControllerHandle500,
  CreateUserCouponControllerHandleMutationRequest,
  CreateUserCouponControllerHandleMutationResponse,
} from "../types/CreateUserCouponControllerHandle.ts";

function getCreateUserCouponControllerHandleUrl() {
  const res = { method: "POST", url: `/user-coupons` as const };
  return res;
}

/**
 * @summary Create a user coupon
 * {@link /user-coupons}
 */
export async function createUserCouponControllerHandle(
  data: CreateUserCouponControllerHandleMutationRequest,
  config: Partial<
    RequestConfig<CreateUserCouponControllerHandleMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const res = await request<
    CreateUserCouponControllerHandleMutationResponse,
    ResponseErrorConfig<
      | CreateUserCouponControllerHandle400
      | CreateUserCouponControllerHandle401
      | CreateUserCouponControllerHandle404
      | CreateUserCouponControllerHandle409
      | CreateUserCouponControllerHandle500
    >,
    CreateUserCouponControllerHandleMutationRequest
  >({
    method: "POST",
    url: getCreateUserCouponControllerHandleUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res;
}
