/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  CreateProductControllerHandle400,
  CreateProductControllerHandle401,
  CreateProductControllerHandle404,
  CreateProductControllerHandle409,
  CreateProductControllerHandle500,
  CreateProductControllerHandleMutationRequest,
  CreateProductControllerHandleMutationResponse,
} from "../types/CreateProductControllerHandle.ts";

function getCreateProductControllerHandleUrl() {
  const res = { method: "POST", url: `/products` as const };
  return res;
}

/**
 * @summary Create a product
 * {@link /products}
 */
export async function createProductControllerHandle(
  data: CreateProductControllerHandleMutationRequest,
  config: Partial<
    RequestConfig<CreateProductControllerHandleMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const res = await request<
    CreateProductControllerHandleMutationResponse,
    ResponseErrorConfig<
      | CreateProductControllerHandle400
      | CreateProductControllerHandle401
      | CreateProductControllerHandle404
      | CreateProductControllerHandle409
      | CreateProductControllerHandle500
    >,
    CreateProductControllerHandleMutationRequest
  >({
    method: "POST",
    url: getCreateProductControllerHandleUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res;
}
