/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  DeleteUserCouponControllerHandle400,
  DeleteUserCouponControllerHandle401,
  DeleteUserCouponControllerHandle404,
  DeleteUserCouponControllerHandle409,
  DeleteUserCouponControllerHandle500,
  DeleteUserCouponControllerHandleMutationResponse,
  DeleteUserCouponControllerHandlePathParams,
} from "../types/DeleteUserCouponControllerHandle.ts";

function getDeleteUserCouponControllerHandleUrl(
  id: DeleteUserCouponControllerHandlePathParams["id"],
) {
  const res = { method: "DELETE", url: `/user-coupons/${id}` as const };
  return res;
}

/**
 * @summary Delete a user coupon
 * {@link /user-coupons/:id}
 */
export async function deleteUserCouponControllerHandle(
  id: DeleteUserCouponControllerHandlePathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteUserCouponControllerHandleMutationResponse,
    ResponseErrorConfig<
      | DeleteUserCouponControllerHandle400
      | DeleteUserCouponControllerHandle401
      | DeleteUserCouponControllerHandle404
      | DeleteUserCouponControllerHandle409
      | DeleteUserCouponControllerHandle500
    >,
    unknown
  >({
    method: "DELETE",
    url: getDeleteUserCouponControllerHandleUrl(id).url.toString(),
    ...requestConfig,
  });
  return res;
}
