/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  DeletePromotionControllerHandle400,
  DeletePromotionControllerHandle401,
  DeletePromotionControllerHandle404,
  DeletePromotionControllerHandle409,
  DeletePromotionControllerHandle500,
  DeletePromotionControllerHandleMutationResponse,
  DeletePromotionControllerHandlePathParams,
} from "../types/DeletePromotionControllerHandle.ts";

function getDeletePromotionControllerHandleUrl(
  id: DeletePromotionControllerHandlePathParams["id"],
) {
  const res = { method: "DELETE", url: `/promotions/${id}` as const };
  return res;
}

/**
 * @summary Delete a promotion
 * {@link /promotions/:id}
 */
export async function deletePromotionControllerHandle(
  id: DeletePromotionControllerHandlePathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeletePromotionControllerHandleMutationResponse,
    ResponseErrorConfig<
      | DeletePromotionControllerHandle400
      | DeletePromotionControllerHandle401
      | DeletePromotionControllerHandle404
      | DeletePromotionControllerHandle409
      | DeletePromotionControllerHandle500
    >,
    unknown
  >({
    method: "DELETE",
    url: getDeletePromotionControllerHandleUrl(id).url.toString(),
    ...requestConfig,
  });
  return res;
}
