/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  DeleteCouponControllerHandle400,
  DeleteCouponControllerHandle401,
  DeleteCouponControllerHandle404,
  DeleteCouponControllerHandle409,
  DeleteCouponControllerHandle500,
  DeleteCouponControllerHandleMutationResponse,
  DeleteCouponControllerHandlePathParams,
} from "../types/DeleteCouponControllerHandle.ts";

function getDeleteCouponControllerHandleUrl(
  id: DeleteCouponControllerHandlePathParams["id"],
) {
  const res = { method: "DELETE", url: `/coupons/${id}` as const };
  return res;
}

/**
 * @summary Delete a coupon
 * {@link /coupons/:id}
 */
export async function deleteCouponControllerHandle(
  id: DeleteCouponControllerHandlePathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteCouponControllerHandleMutationResponse,
    ResponseErrorConfig<
      | DeleteCouponControllerHandle400
      | DeleteCouponControllerHandle401
      | DeleteCouponControllerHandle404
      | DeleteCouponControllerHandle409
      | DeleteCouponControllerHandle500
    >,
    unknown
  >({
    method: "DELETE",
    url: getDeleteCouponControllerHandleUrl(id).url.toString(),
    ...requestConfig,
  });
  return res;
}
