/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  GetCouponsByProductsIdsControllerHandleQueryParams,
  GetCouponsByProductsIdsControllerHandleQueryResponse,
} from "../types/GetCouponsByProductsIdsControllerHandle.ts";

function getGetCouponsByProductsIdsControllerHandleUrl() {
  const res = { method: "GET", url: `/coupons/products` as const };
  return res;
}

/**
 * @summary Get coupons by multiple product IDs
 * {@link /coupons/products}
 */
export async function getCouponsByProductsIdsControllerHandle(
  params: GetCouponsByProductsIdsControllerHandleQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetCouponsByProductsIdsControllerHandleQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetCouponsByProductsIdsControllerHandleUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res;
}
