/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  GetCouponsByProductIdControllerHandlePathParams,
  GetCouponsByProductIdControllerHandleQueryResponse,
} from "../types/GetCouponsByProductIdControllerHandle.ts";

function getGetCouponsByProductIdControllerHandleUrl(
  productId: GetCouponsByProductIdControllerHandlePathParams["productId"],
) {
  const res = { method: "GET", url: `/coupons/product/${productId}` as const };
  return res;
}

/**
 * @summary Get coupons by product ID
 * {@link /coupons/product/:productId}
 */
export async function getCouponsByProductIdControllerHandle(
  productId: GetCouponsByProductIdControllerHandlePathParams["productId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetCouponsByProductIdControllerHandleQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetCouponsByProductIdControllerHandleUrl(productId).url.toString(),
    ...requestConfig,
  });
  return res;
}
