/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  GetCouponControllerHandle400,
  GetCouponControllerHandle401,
  GetCouponControllerHandle404,
  GetCouponControllerHandle409,
  GetCouponControllerHandle500,
  GetCouponControllerHandlePathParams,
  GetCouponControllerHandleQueryResponse,
} from "../types/GetCouponControllerHandle.ts";

function getGetCouponControllerHandleUrl(
  id: GetCouponControllerHandlePathParams["id"],
) {
  const res = { method: "GET", url: `/coupons/${id}` as const };
  return res;
}

/**
 * @summary Get a coupon by ID
 * {@link /coupons/:id}
 */
export async function getCouponControllerHandle(
  id: GetCouponControllerHandlePathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetCouponControllerHandleQueryResponse,
    ResponseErrorConfig<
      | GetCouponControllerHandle400
      | GetCouponControllerHandle401
      | GetCouponControllerHandle404
      | GetCouponControllerHandle409
      | GetCouponControllerHandle500
    >,
    unknown
  >({
    method: "GET",
    url: getGetCouponControllerHandleUrl(id).url.toString(),
    ...requestConfig,
  });
  return res;
}
