/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  GetFeaturedProductsControllerHandle400,
  GetFeaturedProductsControllerHandle401,
  GetFeaturedProductsControllerHandle404,
  GetFeaturedProductsControllerHandle409,
  GetFeaturedProductsControllerHandle500,
  GetFeaturedProductsControllerHandleQueryParams,
  GetFeaturedProductsControllerHandleQueryResponse,
} from "../types/GetFeaturedProductsControllerHandle.ts";

function getGetFeaturedProductsControllerHandleUrl() {
  const res = { method: "GET", url: `/products/featured` as const };
  return res;
}

/**
 * @summary Get featured products from all organizations
 * {@link /products/featured}
 */
export async function getFeaturedProductsControllerHandle(
  params?: GetFeaturedProductsControllerHandleQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetFeaturedProductsControllerHandleQueryResponse,
    ResponseErrorConfig<
      | GetFeaturedProductsControllerHandle400
      | GetFeaturedProductsControllerHandle401
      | GetFeaturedProductsControllerHandle404
      | GetFeaturedProductsControllerHandle409
      | GetFeaturedProductsControllerHandle500
    >,
    unknown
  >({
    method: "GET",
    url: getGetFeaturedProductsControllerHandleUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res;
}
