/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  GetPublicProductsControllerHandle400,
  GetPublicProductsControllerHandle401,
  GetPublicProductsControllerHandle404,
  GetPublicProductsControllerHandle409,
  GetPublicProductsControllerHandle500,
  GetPublicProductsControllerHandleQueryParams,
  GetPublicProductsControllerHandleQueryResponse,
} from "../types/GetPublicProductsControllerHandle.ts";

function getGetPublicProductsControllerHandleUrl() {
  const res = { method: "GET", url: `/products/public` as const };
  return res;
}

/**
 * @summary Get public products from all organizations
 * {@link /products/public}
 */
export async function getPublicProductsControllerHandle(
  params?: GetPublicProductsControllerHandleQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetPublicProductsControllerHandleQueryResponse,
    ResponseErrorConfig<
      | GetPublicProductsControllerHandle400
      | GetPublicProductsControllerHandle401
      | GetPublicProductsControllerHandle404
      | GetPublicProductsControllerHandle409
      | GetPublicProductsControllerHandle500
    >,
    unknown
  >({
    method: "GET",
    url: getGetPublicProductsControllerHandleUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res;
}
