/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  GetProductsByOrganizationControllerHandle400,
  GetProductsByOrganizationControllerHandle401,
  GetProductsByOrganizationControllerHandle404,
  GetProductsByOrganizationControllerHandle409,
  GetProductsByOrganizationControllerHandle500,
  GetProductsByOrganizationControllerHandleQueryParams,
  GetProductsByOrganizationControllerHandleQueryResponse,
} from "../types/GetProductsByOrganizationControllerHandle.ts";

function getGetProductsByOrganizationControllerHandleUrl() {
  const res = { method: "GET", url: `/products/organization` as const };
  return res;
}

/**
 * @summary Get products by organization
 * {@link /products/organization}
 */
export async function getProductsByOrganizationControllerHandle(
  params: GetProductsByOrganizationControllerHandleQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetProductsByOrganizationControllerHandleQueryResponse,
    ResponseErrorConfig<
      | GetProductsByOrganizationControllerHandle400
      | GetProductsByOrganizationControllerHandle401
      | GetProductsByOrganizationControllerHandle404
      | GetProductsByOrganizationControllerHandle409
      | GetProductsByOrganizationControllerHandle500
    >,
    unknown
  >({
    method: "GET",
    url: getGetProductsByOrganizationControllerHandleUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res;
}
