/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  GetPromotionsByProductsIdsControllerHandleQueryParams,
  GetPromotionsByProductsIdsControllerHandleQueryResponse,
} from "../types/GetPromotionsByProductsIdsControllerHandle.ts";

function getGetPromotionsByProductsIdsControllerHandleUrl() {
  const res = { method: "GET", url: `/promotions/products` as const };
  return res;
}

/**
 * @summary Get promotions by product IDs
 * {@link /promotions/products}
 */
export async function getPromotionsByProductsIdsControllerHandle(
  params: GetPromotionsByProductsIdsControllerHandleQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetPromotionsByProductsIdsControllerHandleQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetPromotionsByProductsIdsControllerHandleUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res;
}
