/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  GetPromotionsByProductIdControllerHandlePathParams,
  GetPromotionsByProductIdControllerHandleQueryResponse,
} from "../types/GetPromotionsByProductIdControllerHandle.ts";

function getGetPromotionsByProductIdControllerHandleUrl(
  productId: GetPromotionsByProductIdControllerHandlePathParams["productId"],
) {
  const res = {
    method: "GET",
    url: `/promotions/product/${productId}` as const,
  };
  return res;
}

/**
 * @summary Get promotions by product ID
 * {@link /promotions/product/:productId}
 */
export async function getPromotionsByProductIdControllerHandle(
  productId: GetPromotionsByProductIdControllerHandlePathParams["productId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetPromotionsByProductIdControllerHandleQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetPromotionsByProductIdControllerHandleUrl(
      productId,
    ).url.toString(),
    ...requestConfig,
  });
  return res;
}
