/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  GetPromotionControllerHandle400,
  GetPromotionControllerHandle401,
  GetPromotionControllerHandle404,
  GetPromotionControllerHandle409,
  GetPromotionControllerHandle500,
  GetPromotionControllerHandlePathParams,
  GetPromotionControllerHandleQueryResponse,
} from "../types/GetPromotionControllerHandle.ts";

function getGetPromotionControllerHandleUrl(
  id: GetPromotionControllerHandlePathParams["id"],
) {
  const res = { method: "GET", url: `/promotions/${id}` as const };
  return res;
}

/**
 * @summary Get a promotion by ID
 * {@link /promotions/:id}
 */
export async function getPromotionControllerHandle(
  id: GetPromotionControllerHandlePathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetPromotionControllerHandleQueryResponse,
    ResponseErrorConfig<
      | GetPromotionControllerHandle400
      | GetPromotionControllerHandle401
      | GetPromotionControllerHandle404
      | GetPromotionControllerHandle409
      | GetPromotionControllerHandle500
    >,
    unknown
  >({
    method: "GET",
    url: getGetPromotionControllerHandleUrl(id).url.toString(),
    ...requestConfig,
  });
  return res;
}
