/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  GetStoreFrontControllerHandle400,
  GetStoreFrontControllerHandle401,
  GetStoreFrontControllerHandle404,
  GetStoreFrontControllerHandle409,
  GetStoreFrontControllerHandle500,
  GetStoreFrontControllerHandleQueryParams,
  GetStoreFrontControllerHandleQueryResponse,
} from "../types/GetStoreFrontControllerHandle.ts";

function getGetStoreFrontControllerHandleUrl() {
  const res = { method: "GET", url: `/store-front` as const };
  return res;
}

/**
 * @summary Get a store front
 * {@link /store-front}
 */
export async function getStoreFrontControllerHandle(
  params: GetStoreFrontControllerHandleQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetStoreFrontControllerHandleQueryResponse,
    ResponseErrorConfig<
      | GetStoreFrontControllerHandle400
      | GetStoreFrontControllerHandle401
      | GetStoreFrontControllerHandle404
      | GetStoreFrontControllerHandle409
      | GetStoreFrontControllerHandle500
    >,
    unknown
  >({
    method: "GET",
    url: getGetStoreFrontControllerHandleUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res;
}
