/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  GetUserCouponsByCouponsIdsControllerHandleQueryParams,
  GetUserCouponsByCouponsIdsControllerHandleQueryResponse,
} from "../types/GetUserCouponsByCouponsIdsControllerHandle.ts";

function getGetUserCouponsByCouponsIdsControllerHandleUrl() {
  const res = { method: "GET", url: `/user-coupons/coupons` as const };
  return res;
}

/**
 * @summary Get user coupons by coupon IDs
 * {@link /user-coupons/coupons}
 */
export async function getUserCouponsByCouponsIdsControllerHandle(
  params: GetUserCouponsByCouponsIdsControllerHandleQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetUserCouponsByCouponsIdsControllerHandleQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetUserCouponsByCouponsIdsControllerHandleUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res;
}
