/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  GetUserCouponsByCouponIdControllerHandlePathParams,
  GetUserCouponsByCouponIdControllerHandleQueryResponse,
} from "../types/GetUserCouponsByCouponIdControllerHandle.ts";

function getGetUserCouponsByCouponIdControllerHandleUrl(
  couponId: GetUserCouponsByCouponIdControllerHandlePathParams["couponId"],
) {
  const res = {
    method: "GET",
    url: `/user-coupons/coupon/${couponId}` as const,
  };
  return res;
}

/**
 * @summary Get user coupons by coupon ID
 * {@link /user-coupons/coupon/:couponId}
 */
export async function getUserCouponsByCouponIdControllerHandle(
  couponId: GetUserCouponsByCouponIdControllerHandlePathParams["couponId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetUserCouponsByCouponIdControllerHandleQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetUserCouponsByCouponIdControllerHandleUrl(
      couponId,
    ).url.toString(),
    ...requestConfig,
  });
  return res;
}
