/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  GetUserCouponControllerHandle400,
  GetUserCouponControllerHandle401,
  GetUserCouponControllerHandle404,
  GetUserCouponControllerHandle409,
  GetUserCouponControllerHandle500,
  GetUserCouponControllerHandlePathParams,
  GetUserCouponControllerHandleQueryResponse,
} from "../types/GetUserCouponControllerHandle.ts";

function getGetUserCouponControllerHandleUrl(
  id: GetUserCouponControllerHandlePathParams["id"],
) {
  const res = { method: "GET", url: `/user-coupons/${id}` as const };
  return res;
}

/**
 * @summary Get a user coupon by ID
 * {@link /user-coupons/:id}
 */
export async function getUserCouponControllerHandle(
  id: GetUserCouponControllerHandlePathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetUserCouponControllerHandleQueryResponse,
    ResponseErrorConfig<
      | GetUserCouponControllerHandle400
      | GetUserCouponControllerHandle401
      | GetUserCouponControllerHandle404
      | GetUserCouponControllerHandle409
      | GetUserCouponControllerHandle500
    >,
    unknown
  >({
    method: "GET",
    url: getGetUserCouponControllerHandleUrl(id).url.toString(),
    ...requestConfig,
  });
  return res;
}
