/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  SearchUserCouponsControllerHandle400,
  SearchUserCouponsControllerHandle401,
  SearchUserCouponsControllerHandle404,
  SearchUserCouponsControllerHandle409,
  SearchUserCouponsControllerHandle500,
  SearchUserCouponsControllerHandleQueryParams,
  SearchUserCouponsControllerHandleQueryResponse,
} from "../types/SearchUserCouponsControllerHandle.ts";

function getSearchUserCouponsControllerHandleUrl() {
  const res = { method: "GET", url: `/user-coupons` as const };
  return res;
}

/**
 * @summary Search user coupons with pagination
 * {@link /user-coupons}
 */
export async function searchUserCouponsControllerHandle(
  params?: SearchUserCouponsControllerHandleQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    SearchUserCouponsControllerHandleQueryResponse,
    ResponseErrorConfig<
      | SearchUserCouponsControllerHandle400
      | SearchUserCouponsControllerHandle401
      | SearchUserCouponsControllerHandle404
      | SearchUserCouponsControllerHandle409
      | SearchUserCouponsControllerHandle500
    >,
    unknown
  >({
    method: "GET",
    url: getSearchUserCouponsControllerHandleUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res;
}
