/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  SearchPromotionsControllerHandle400,
  SearchPromotionsControllerHandle401,
  SearchPromotionsControllerHandle404,
  SearchPromotionsControllerHandle409,
  SearchPromotionsControllerHandle500,
  SearchPromotionsControllerHandleQueryParams,
  SearchPromotionsControllerHandleQueryResponse,
} from "../types/SearchPromotionsControllerHandle.ts";

function getSearchPromotionsControllerHandleUrl() {
  const res = { method: "GET", url: `/promotions` as const };
  return res;
}

/**
 * @summary Search promotions with advanced filters
 * {@link /promotions}
 */
export async function searchPromotionsControllerHandle(
  params?: SearchPromotionsControllerHandleQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    SearchPromotionsControllerHandleQueryResponse,
    ResponseErrorConfig<
      | SearchPromotionsControllerHandle400
      | SearchPromotionsControllerHandle401
      | SearchPromotionsControllerHandle404
      | SearchPromotionsControllerHandle409
      | SearchPromotionsControllerHandle500
    >,
    unknown
  >({
    method: "GET",
    url: getSearchPromotionsControllerHandleUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res;
}
