/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  SearchProductControllerHandle400,
  SearchProductControllerHandle401,
  SearchProductControllerHandle404,
  SearchProductControllerHandle409,
  SearchProductControllerHandle500,
  SearchProductControllerHandleQueryParams,
  SearchProductControllerHandleQueryResponse,
} from "../types/SearchProductControllerHandle.ts";

function getSearchProductControllerHandleUrl() {
  const res = { method: "GET", url: `/products/search` as const };
  return res;
}

/**
 * @summary Search products
 * {@link /products/search}
 */
export async function searchProductControllerHandle(
  params?: SearchProductControllerHandleQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    SearchProductControllerHandleQueryResponse,
    ResponseErrorConfig<
      | SearchProductControllerHandle400
      | SearchProductControllerHandle401
      | SearchProductControllerHandle404
      | SearchProductControllerHandle409
      | SearchProductControllerHandle500
    >,
    unknown
  >({
    method: "GET",
    url: getSearchProductControllerHandleUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res;
}
