/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  SearchCouponsControllerHandle400,
  SearchCouponsControllerHandle401,
  SearchCouponsControllerHandle404,
  SearchCouponsControllerHandle409,
  SearchCouponsControllerHandle500,
  SearchCouponsControllerHandleQueryParams,
  SearchCouponsControllerHandleQueryResponse,
} from "../types/SearchCouponsControllerHandle.ts";

function getSearchCouponsControllerHandleUrl() {
  const res = { method: "GET", url: `/coupons` as const };
  return res;
}

/**
 * @summary Search coupons with advanced filters
 * {@link /coupons}
 */
export async function searchCouponsControllerHandle(
  params?: SearchCouponsControllerHandleQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    SearchCouponsControllerHandleQueryResponse,
    ResponseErrorConfig<
      | SearchCouponsControllerHandle400
      | SearchCouponsControllerHandle401
      | SearchCouponsControllerHandle404
      | SearchCouponsControllerHandle409
      | SearchCouponsControllerHandle500
    >,
    unknown
  >({
    method: "GET",
    url: getSearchCouponsControllerHandleUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res;
}
