/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  SearchOrganizationsControllerHandleQueryParams,
  SearchOrganizationsControllerHandleQueryResponse,
} from "../types/SearchOrganizationsControllerHandle.ts";

function getSearchOrganizationsControllerHandleUrl() {
  const res = { method: "GET", url: `/organization/search` as const };
  return res;
}

/**
 * @summary Search organizations with pagination
 * {@link /organization/search}
 */
export async function searchOrganizationsControllerHandle(
  params?: SearchOrganizationsControllerHandleQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    SearchOrganizationsControllerHandleQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getSearchOrganizationsControllerHandleUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res;
}
