/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  UpdateStoreFrontControllerHandle400,
  UpdateStoreFrontControllerHandle401,
  UpdateStoreFrontControllerHandle404,
  UpdateStoreFrontControllerHandle409,
  UpdateStoreFrontControllerHandle500,
  UpdateStoreFrontControllerHandleMutationRequest,
  UpdateStoreFrontControllerHandleMutationResponse,
} from "../types/UpdateStoreFrontControllerHandle.ts";

function getUpdateStoreFrontControllerHandleUrl() {
  const res = { method: "PATCH", url: `/store-front` as const };
  return res;
}

/**
 * @summary Update a store front
 * {@link /store-front}
 */
export async function updateStoreFrontControllerHandle(
  data: UpdateStoreFrontControllerHandleMutationRequest,
  config: Partial<
    RequestConfig<UpdateStoreFrontControllerHandleMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const res = await request<
    UpdateStoreFrontControllerHandleMutationResponse,
    ResponseErrorConfig<
      | UpdateStoreFrontControllerHandle400
      | UpdateStoreFrontControllerHandle401
      | UpdateStoreFrontControllerHandle404
      | UpdateStoreFrontControllerHandle409
      | UpdateStoreFrontControllerHandle500
    >,
    UpdateStoreFrontControllerHandleMutationRequest
  >({
    method: "PATCH",
    url: getUpdateStoreFrontControllerHandleUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res;
}
