/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  UpdatePromotionControllerHandle400,
  UpdatePromotionControllerHandle401,
  UpdatePromotionControllerHandle404,
  UpdatePromotionControllerHandle409,
  UpdatePromotionControllerHandle500,
  UpdatePromotionControllerHandleMutationRequest,
  UpdatePromotionControllerHandleMutationResponse,
  UpdatePromotionControllerHandlePathParams,
} from "../types/UpdatePromotionControllerHandle.ts";

function getUpdatePromotionControllerHandleUrl(
  id: UpdatePromotionControllerHandlePathParams["id"],
) {
  const res = { method: "PATCH", url: `/promotions/${id}` as const };
  return res;
}

/**
 * @summary Update a promotion
 * {@link /promotions/:id}
 */
export async function updatePromotionControllerHandle(
  id: UpdatePromotionControllerHandlePathParams["id"],
  data?: UpdatePromotionControllerHandleMutationRequest,
  config: Partial<
    RequestConfig<UpdatePromotionControllerHandleMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const res = await request<
    UpdatePromotionControllerHandleMutationResponse,
    ResponseErrorConfig<
      | UpdatePromotionControllerHandle400
      | UpdatePromotionControllerHandle401
      | UpdatePromotionControllerHandle404
      | UpdatePromotionControllerHandle409
      | UpdatePromotionControllerHandle500
    >,
    UpdatePromotionControllerHandleMutationRequest
  >({
    method: "PATCH",
    url: getUpdatePromotionControllerHandleUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res;
}
