/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import fetch from "@/lib/api-client";
import type {
  UpdateCouponControllerHandle400,
  UpdateCouponControllerHandle401,
  UpdateCouponControllerHandle404,
  UpdateCouponControllerHandle409,
  UpdateCouponControllerHandle500,
  UpdateCouponControllerHandleMutationRequest,
  UpdateCouponControllerHandleMutationResponse,
  UpdateCouponControllerHandlePathParams,
} from "../types/UpdateCouponControllerHandle.ts";

function getUpdateCouponControllerHandleUrl(
  id: UpdateCouponControllerHandlePathParams["id"],
) {
  const res = { method: "PATCH", url: `/coupons/${id}` as const };
  return res;
}

/**
 * @summary Update a coupon
 * {@link /coupons/:id}
 */
export async function updateCouponControllerHandle(
  id: UpdateCouponControllerHandlePathParams["id"],
  data?: UpdateCouponControllerHandleMutationRequest,
  config: Partial<
    RequestConfig<UpdateCouponControllerHandleMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const res = await request<
    UpdateCouponControllerHandleMutationResponse,
    ResponseErrorConfig<
      | UpdateCouponControllerHandle400
      | UpdateCouponControllerHandle401
      | UpdateCouponControllerHandle404
      | UpdateCouponControllerHandle409
      | UpdateCouponControllerHandle500
    >,
    UpdateCouponControllerHandleMutationRequest
  >({
    method: "PATCH",
    url: getUpdateCouponControllerHandleUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res;
}
