/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { CreateCouponBodyDto } from "./CreateCouponBodyDto.ts";
import type { CreateCouponResponseDto } from "./CreateCouponResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

/**
 * @description Coupon created successfully
 */
export type CreateCouponControllerHandle201 = CreateCouponResponseDto;

/**
 * @description Bad Request
 */
export type CreateCouponControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type CreateCouponControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type CreateCouponControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type CreateCouponControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type CreateCouponControllerHandle500 = InternalServerErrorDto;

export type CreateCouponControllerHandleMutationRequest = CreateCouponBodyDto;

export type CreateCouponControllerHandleMutationResponse =
  CreateCouponControllerHandle201;

export type CreateCouponControllerHandleMutation = {
  Response: CreateCouponControllerHandle201;
  Request: CreateCouponControllerHandleMutationRequest;
  Errors:
    | CreateCouponControllerHandle400
    | CreateCouponControllerHandle401
    | CreateCouponControllerHandle404
    | CreateCouponControllerHandle409
    | CreateCouponControllerHandle500;
};
