/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const createStoreFrontBodyDtoThemeEnum = {
  DEFAULT: "DEFAULT",
  AMETHYST_HAZE: "AMETHYST_HAZE",
  SOLAR_DUSK: "SOLAR_DUSK",
} as const;

export type CreateStoreFrontBodyDtoThemeEnum =
  (typeof createStoreFrontBodyDtoThemeEnum)[keyof typeof createStoreFrontBodyDtoThemeEnum];

export type CreateStoreFrontBodyDto = {
  /**
   * @type string
   */
  organizationId: string;
  /**
   * @type string
   */
  logoImage: string;
  /**
   * @type string
   */
  bannerImage: string;
  /**
   * @type string | undefined
   */
  whatsappNumber?: string;
  /**
   * @type string
   */
  location: string;
  /**
   * @default "DEFAULT"
   * @type string | undefined
   */
  theme?: CreateStoreFrontBodyDtoThemeEnum;
};
