/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateUserCouponResponseDto = {
  /**
   * @type object
   */
  userCoupon: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    couponId: string;
    /**
     * @type string
     */
    userId: string;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};
