/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { CreatePromotionBodyDto } from "./CreatePromotionBodyDto.ts";
import type { CreatePromotionResponseDto } from "./CreatePromotionResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

/**
 * @description Promotion created successfully
 */
export type CreatePromotionControllerHandle201 = CreatePromotionResponseDto;

/**
 * @description Bad Request
 */
export type CreatePromotionControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type CreatePromotionControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type CreatePromotionControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type CreatePromotionControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type CreatePromotionControllerHandle500 = InternalServerErrorDto;

export type CreatePromotionControllerHandleMutationRequest =
  CreatePromotionBodyDto;

export type CreatePromotionControllerHandleMutationResponse =
  CreatePromotionControllerHandle201;

export type CreatePromotionControllerHandleMutation = {
  Response: CreatePromotionControllerHandle201;
  Request: CreatePromotionControllerHandleMutationRequest;
  Errors:
    | CreatePromotionControllerHandle400
    | CreatePromotionControllerHandle401
    | CreatePromotionControllerHandle404
    | CreatePromotionControllerHandle409
    | CreatePromotionControllerHandle500;
};
