/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreatePromotionBodyDto = {
  /**
   * @type string
   */
  productId: string;
  /**
   * @minLength 0
   * @maxLength 100
   * @type number
   */
  discountPercentage: number;
  /**
   * @type string, date-time
   */
  validUntil: string;
};
