/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const storeFrontThemeEnum = {
  DEFAULT: "DEFAULT",
  AMETHYST_HAZE: "AMETHYST_HAZE",
  SOLAR_DUSK: "SOLAR_DUSK",
} as const;

export type StoreFrontThemeEnum =
  (typeof storeFrontThemeEnum)[keyof typeof storeFrontThemeEnum];

export type CreateStoreFrontResponseDto = {
  /**
   * @type object
   */
  storeFront: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    organizationId: string;
    /**
     * @type string
     */
    logoImageUrl: string;
    /**
     * @type string
     */
    logoImageBlurData: string;
    /**
     * @type string
     */
    bannerImageUrl: string;
    /**
     * @type string
     */
    bannerImageBlurData: string;
    /**
     * @type string | undefined
     */
    whatsappNumber?: string;
    /**
     * @type string
     */
    location: string;
    /**
     * @type string
     */
    theme: StoreFrontThemeEnum;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};
