/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { CreateUserCouponBodyDto } from "./CreateUserCouponBodyDto.ts";
import type { CreateUserCouponResponseDto } from "./CreateUserCouponResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

/**
 * @description User coupon created successfully
 */
export type CreateUserCouponControllerHandle201 = CreateUserCouponResponseDto;

/**
 * @description Bad Request
 */
export type CreateUserCouponControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type CreateUserCouponControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type CreateUserCouponControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type CreateUserCouponControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type CreateUserCouponControllerHandle500 = InternalServerErrorDto;

export type CreateUserCouponControllerHandleMutationRequest =
  CreateUserCouponBodyDto;

export type CreateUserCouponControllerHandleMutationResponse =
  CreateUserCouponControllerHandle201;

export type CreateUserCouponControllerHandleMutation = {
  Response: CreateUserCouponControllerHandle201;
  Request: CreateUserCouponControllerHandleMutationRequest;
  Errors:
    | CreateUserCouponControllerHandle400
    | CreateUserCouponControllerHandle401
    | CreateUserCouponControllerHandle404
    | CreateUserCouponControllerHandle409
    | CreateUserCouponControllerHandle500;
};
