/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateProductBodyDto = {
  /**
   * @type string
   */
  organizationId: string;
  /**
   * @type string
   */
  image: string;
  /**
   * @type string
   */
  title: string;
  /**
   * @type string
   */
  description: string;
  /**
   * @type number
   */
  price: number;
};
