/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { CreateStoreFrontBodyDto } from "./CreateStoreFrontBodyDto.ts";
import type { CreateStoreFrontResponseDto } from "./CreateStoreFrontResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

/**
 * @description Store front created successfully
 */
export type CreateStoreFrontControllerHandle201 = CreateStoreFrontResponseDto;

/**
 * @description Bad Request
 */
export type CreateStoreFrontControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type CreateStoreFrontControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type CreateStoreFrontControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type CreateStoreFrontControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type CreateStoreFrontControllerHandle500 = InternalServerErrorDto;

export type CreateStoreFrontControllerHandleMutationRequest =
  CreateStoreFrontBodyDto;

export type CreateStoreFrontControllerHandleMutationResponse =
  CreateStoreFrontControllerHandle201;

export type CreateStoreFrontControllerHandleMutation = {
  Response: CreateStoreFrontControllerHandle201;
  Request: CreateStoreFrontControllerHandleMutationRequest;
  Errors:
    | CreateStoreFrontControllerHandle400
    | CreateStoreFrontControllerHandle401
    | CreateStoreFrontControllerHandle404
    | CreateStoreFrontControllerHandle409
    | CreateStoreFrontControllerHandle500;
};
