/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { CreateProductBodyDto } from "./CreateProductBodyDto.ts";
import type { CreateProductResponseDto } from "./CreateProductResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

/**
 * @description Product created successfully
 */
export type CreateProductControllerHandle201 = CreateProductResponseDto;

/**
 * @description Bad Request
 */
export type CreateProductControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type CreateProductControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type CreateProductControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type CreateProductControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type CreateProductControllerHandle500 = InternalServerErrorDto;

export type CreateProductControllerHandleMutationRequest = CreateProductBodyDto;

export type CreateProductControllerHandleMutationResponse =
  CreateProductControllerHandle201;

export type CreateProductControllerHandleMutation = {
  Response: CreateProductControllerHandle201;
  Request: CreateProductControllerHandleMutationRequest;
  Errors:
    | CreateProductControllerHandle400
    | CreateProductControllerHandle401
    | CreateProductControllerHandle404
    | CreateProductControllerHandle409
    | CreateProductControllerHandle500;
};
