/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { DeleteUserCouponResponseDto } from "./DeleteUserCouponResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export type DeleteUserCouponControllerHandlePathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description User coupon deleted successfully
 */
export type DeleteUserCouponControllerHandle200 = DeleteUserCouponResponseDto;

/**
 * @description Bad Request
 */
export type DeleteUserCouponControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type DeleteUserCouponControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type DeleteUserCouponControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type DeleteUserCouponControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type DeleteUserCouponControllerHandle500 = InternalServerErrorDto;

export type DeleteUserCouponControllerHandleMutationResponse =
  DeleteUserCouponControllerHandle200;

export type DeleteUserCouponControllerHandleMutation = {
  Response: DeleteUserCouponControllerHandle200;
  PathParams: DeleteUserCouponControllerHandlePathParams;
  Errors:
    | DeleteUserCouponControllerHandle400
    | DeleteUserCouponControllerHandle401
    | DeleteUserCouponControllerHandle404
    | DeleteUserCouponControllerHandle409
    | DeleteUserCouponControllerHandle500;
};
