/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { DeleteCouponResponseDto } from "./DeleteCouponResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export type DeleteCouponControllerHandlePathParams = {
  /**
   * @description Coupon ID
   * @type string
   */
  id: string;
};

/**
 * @description Coupon deleted successfully
 */
export type DeleteCouponControllerHandle200 = DeleteCouponResponseDto;

/**
 * @description Bad Request
 */
export type DeleteCouponControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type DeleteCouponControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type DeleteCouponControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type DeleteCouponControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type DeleteCouponControllerHandle500 = InternalServerErrorDto;

export type DeleteCouponControllerHandleMutationResponse =
  DeleteCouponControllerHandle200;

export type DeleteCouponControllerHandleMutation = {
  Response: DeleteCouponControllerHandle200;
  PathParams: DeleteCouponControllerHandlePathParams;
  Errors:
    | DeleteCouponControllerHandle400
    | DeleteCouponControllerHandle401
    | DeleteCouponControllerHandle404
    | DeleteCouponControllerHandle409
    | DeleteCouponControllerHandle500;
};
