/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { DeletePromotionResponseDto } from "./DeletePromotionResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export type DeletePromotionControllerHandlePathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Promotion deleted successfully
 */
export type DeletePromotionControllerHandle200 = DeletePromotionResponseDto;

/**
 * @description Bad Request
 */
export type DeletePromotionControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type DeletePromotionControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type DeletePromotionControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type DeletePromotionControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type DeletePromotionControllerHandle500 = InternalServerErrorDto;

export type DeletePromotionControllerHandleMutationResponse =
  DeletePromotionControllerHandle200;

export type DeletePromotionControllerHandleMutation = {
  Response: DeletePromotionControllerHandle200;
  PathParams: DeletePromotionControllerHandlePathParams;
  Errors:
    | DeletePromotionControllerHandle400
    | DeletePromotionControllerHandle401
    | DeletePromotionControllerHandle404
    | DeletePromotionControllerHandle409
    | DeletePromotionControllerHandle500;
};
