/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { DeleteProductResponseDto } from "./DeleteProductResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export type DeleteProductControllerHandlePathParams = {
  /**
   * @description The ID of the product to delete
   * @type string
   */
  productId: string;
};

/**
 * @description Product deleted successfully
 */
export type DeleteProductControllerHandle200 = DeleteProductResponseDto;

/**
 * @description Bad Request
 */
export type DeleteProductControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type DeleteProductControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type DeleteProductControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type DeleteProductControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type DeleteProductControllerHandle500 = InternalServerErrorDto;

export type DeleteProductControllerHandleMutationResponse =
  DeleteProductControllerHandle200;

export type DeleteProductControllerHandleMutation = {
  Response: DeleteProductControllerHandle200;
  PathParams: DeleteProductControllerHandlePathParams;
  Errors:
    | DeleteProductControllerHandle400
    | DeleteProductControllerHandle401
    | DeleteProductControllerHandle404
    | DeleteProductControllerHandle409
    | DeleteProductControllerHandle500;
};
