/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { GetCouponResponseDto } from "./GetCouponResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export type GetCouponControllerHandlePathParams = {
  /**
   * @description Coupon ID
   * @type string
   */
  id: string;
};

/**
 * @description Coupon retrieved successfully
 */
export type GetCouponControllerHandle200 = GetCouponResponseDto;

/**
 * @description Bad Request
 */
export type GetCouponControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type GetCouponControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type GetCouponControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type GetCouponControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type GetCouponControllerHandle500 = InternalServerErrorDto;

export type GetCouponControllerHandleQueryResponse =
  GetCouponControllerHandle200;

export type GetCouponControllerHandleQuery = {
  Response: GetCouponControllerHandle200;
  PathParams: GetCouponControllerHandlePathParams;
  Errors:
    | GetCouponControllerHandle400
    | GetCouponControllerHandle401
    | GetCouponControllerHandle404
    | GetCouponControllerHandle409
    | GetCouponControllerHandle500;
};
