/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetCouponsByProductsIdsResponseDto } from "./GetCouponsByProductsIdsResponseDto.ts";

export type GetCouponsByProductsIdsControllerHandleQueryParams = {
  /**
   * @type array
   */
  productIds: string[];
};

/**
 * @description Coupons retrieved successfully
 */
export type GetCouponsByProductsIdsControllerHandle200 =
  GetCouponsByProductsIdsResponseDto;

export type GetCouponsByProductsIdsControllerHandleQueryResponse =
  GetCouponsByProductsIdsControllerHandle200;

export type GetCouponsByProductsIdsControllerHandleQuery = {
  Response: GetCouponsByProductsIdsControllerHandle200;
  QueryParams: GetCouponsByProductsIdsControllerHandleQueryParams;
  Errors: any;
};
