/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetCouponsByProductIdResponseDto } from "./GetCouponsByProductIdResponseDto.ts";

export type GetCouponsByProductIdControllerHandlePathParams = {
  /**
   * @type string
   */
  productId: string;
};

/**
 * @description Coupons retrieved successfully
 */
export type GetCouponsByProductIdControllerHandle200 =
  GetCouponsByProductIdResponseDto;

export type GetCouponsByProductIdControllerHandleQueryResponse =
  GetCouponsByProductIdControllerHandle200;

export type GetCouponsByProductIdControllerHandleQuery = {
  Response: GetCouponsByProductIdControllerHandle200;
  PathParams: GetCouponsByProductIdControllerHandlePathParams;
  Errors: any;
};
