/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { GetFeaturedProductsResponseDto } from "./GetFeaturedProductsResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export const getFeaturedProductsControllerHandleQueryParamsOrderDirectionEnum =
  {
    asc: "asc",
    desc: "desc",
  } as const;

export type GetFeaturedProductsControllerHandleQueryParamsOrderDirectionEnum =
  (typeof getFeaturedProductsControllerHandleQueryParamsOrderDirectionEnum)[keyof typeof getFeaturedProductsControllerHandleQueryParamsOrderDirectionEnum];

export const getFeaturedProductsControllerHandleQueryParamsOrderByEnum = {
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  title: "title",
  price: "price",
} as const;

export type GetFeaturedProductsControllerHandleQueryParamsOrderByEnum =
  (typeof getFeaturedProductsControllerHandleQueryParamsOrderByEnum)[keyof typeof getFeaturedProductsControllerHandleQueryParamsOrderByEnum];

export type GetFeaturedProductsControllerHandleQueryParams = {
  /**
   * @description Maximum number of featured products to return
   * @minLength 1
   * @maxLength 100
   * @default 20
   * @type number | undefined
   */
  limit?: number;
  /**
   * @type string | undefined
   */
  orderDirection?: GetFeaturedProductsControllerHandleQueryParamsOrderDirectionEnum;
  /**
   * @type string | undefined
   */
  orderBy?: GetFeaturedProductsControllerHandleQueryParamsOrderByEnum;
};

/**
 * @description Returns featured products from all organizations
 */
export type GetFeaturedProductsControllerHandle200 =
  GetFeaturedProductsResponseDto;

/**
 * @description Bad Request
 */
export type GetFeaturedProductsControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type GetFeaturedProductsControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type GetFeaturedProductsControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type GetFeaturedProductsControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type GetFeaturedProductsControllerHandle500 = InternalServerErrorDto;

export type GetFeaturedProductsControllerHandleQueryResponse =
  GetFeaturedProductsControllerHandle200;

export type GetFeaturedProductsControllerHandleQuery = {
  Response: GetFeaturedProductsControllerHandle200;
  QueryParams: GetFeaturedProductsControllerHandleQueryParams;
  Errors:
    | GetFeaturedProductsControllerHandle400
    | GetFeaturedProductsControllerHandle401
    | GetFeaturedProductsControllerHandle404
    | GetFeaturedProductsControllerHandle409
    | GetFeaturedProductsControllerHandle500;
};
