/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetOrganizationBySlugResponseDto = {
  /**
   * @type object
   */
  organization: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    name: string;
    /**
     * @minLength 3
     * @maxLength 255
     * @type string | undefined
     */
    slug?: string;
    /**
     * @type string | undefined
     */
    logo?: string;
    /**
     * @type string | undefined
     */
    metadata?: string;
    /**
     * @type string
     */
    createdAt?: string | null;
    /**
     * @type string
     */
    updatedAt?: string | null;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};
