/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { GetOrganizationBySlugResponseDto } from "./GetOrganizationBySlugResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export type GetOrganizationBySlugControllerHandlePathParams = {
  /**
   * @description Organization slug
   * @type string
   */
  slug: string;
};

/**
 * @description Returns the organization
 */
export type GetOrganizationBySlugControllerHandle200 =
  GetOrganizationBySlugResponseDto;

/**
 * @description Bad Request
 */
export type GetOrganizationBySlugControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type GetOrganizationBySlugControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type GetOrganizationBySlugControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type GetOrganizationBySlugControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type GetOrganizationBySlugControllerHandle500 = InternalServerErrorDto;

export type GetOrganizationBySlugControllerHandleQueryResponse =
  GetOrganizationBySlugControllerHandle200;

export type GetOrganizationBySlugControllerHandleQuery = {
  Response: GetOrganizationBySlugControllerHandle200;
  PathParams: GetOrganizationBySlugControllerHandlePathParams;
  Errors:
    | GetOrganizationBySlugControllerHandle400
    | GetOrganizationBySlugControllerHandle401
    | GetOrganizationBySlugControllerHandle404
    | GetOrganizationBySlugControllerHandle409
    | GetOrganizationBySlugControllerHandle500;
};
