/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetPromotionsByProductIdResponseDto = {
  /**
   * @type array
   */
  promotions: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type number
     */
    discountPercentage: number;
    /**
     * @type string
     */
    productId: string;
    /**
     * @type string
     */
    userId: string;
    /**
     * @type string
     */
    validUntil?: string | null;
    /**
     * @type string
     */
    createdAt?: string | null;
    /**
     * @type string
     */
    updatedAt?: string | null;
  }[];
};
