/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetPromotionsByProductsIdsResponseDto } from "./GetPromotionsByProductsIdsResponseDto.ts";

export type GetPromotionsByProductsIdsControllerHandleQueryParams = {
  /**
   * @description Array of product IDs
   * @type array
   */
  productIds: string[];
};

/**
 * @description Promotions retrieved successfully
 */
export type GetPromotionsByProductsIdsControllerHandle200 =
  GetPromotionsByProductsIdsResponseDto;

export type GetPromotionsByProductsIdsControllerHandleQueryResponse =
  GetPromotionsByProductsIdsControllerHandle200;

export type GetPromotionsByProductsIdsControllerHandleQuery = {
  Response: GetPromotionsByProductsIdsControllerHandle200;
  QueryParams: GetPromotionsByProductsIdsControllerHandleQueryParams;
  Errors: any;
};
