/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { GetProductResponseDto } from "./GetProductResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export type GetProductControllerHandlePathParams = {
  /**
   * @description The ID of the product to retrieve
   * @type string
   */
  productId: string;
};

/**
 * @description Returns the product
 */
export type GetProductControllerHandle200 = GetProductResponseDto;

/**
 * @description Bad Request
 */
export type GetProductControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type GetProductControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type GetProductControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type GetProductControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type GetProductControllerHandle500 = InternalServerErrorDto;

export type GetProductControllerHandleQueryResponse =
  GetProductControllerHandle200;

export type GetProductControllerHandleQuery = {
  Response: GetProductControllerHandle200;
  PathParams: GetProductControllerHandlePathParams;
  Errors:
    | GetProductControllerHandle400
    | GetProductControllerHandle401
    | GetProductControllerHandle404
    | GetProductControllerHandle409
    | GetProductControllerHandle500;
};
