/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetPromotionsByProductIdResponseDto } from "./GetPromotionsByProductIdResponseDto.ts";

export type GetPromotionsByProductIdControllerHandlePathParams = {
  /**
   * @type string
   */
  productId: string;
};

/**
 * @description Promotions retrieved successfully
 */
export type GetPromotionsByProductIdControllerHandle200 =
  GetPromotionsByProductIdResponseDto;

export type GetPromotionsByProductIdControllerHandleQueryResponse =
  GetPromotionsByProductIdControllerHandle200;

export type GetPromotionsByProductIdControllerHandleQuery = {
  Response: GetPromotionsByProductIdControllerHandle200;
  PathParams: GetPromotionsByProductIdControllerHandlePathParams;
  Errors: any;
};
