/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { GetPromotionResponseDto } from "./GetPromotionResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export type GetPromotionControllerHandlePathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Promotion retrieved successfully
 */
export type GetPromotionControllerHandle200 = GetPromotionResponseDto;

/**
 * @description Bad Request
 */
export type GetPromotionControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type GetPromotionControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type GetPromotionControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type GetPromotionControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type GetPromotionControllerHandle500 = InternalServerErrorDto;

export type GetPromotionControllerHandleQueryResponse =
  GetPromotionControllerHandle200;

export type GetPromotionControllerHandleQuery = {
  Response: GetPromotionControllerHandle200;
  PathParams: GetPromotionControllerHandlePathParams;
  Errors:
    | GetPromotionControllerHandle400
    | GetPromotionControllerHandle401
    | GetPromotionControllerHandle404
    | GetPromotionControllerHandle409
    | GetPromotionControllerHandle500;
};
