/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { GetStoreFrontResponseDto } from "./GetStoreFrontResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export type GetStoreFrontControllerHandleQueryParams = {
  /**
   * @type string
   */
  organizationId: string;
};

/**
 * @description Returns the store front
 */
export type GetStoreFrontControllerHandle200 = GetStoreFrontResponseDto;

/**
 * @description Bad Request
 */
export type GetStoreFrontControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type GetStoreFrontControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type GetStoreFrontControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type GetStoreFrontControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type GetStoreFrontControllerHandle500 = InternalServerErrorDto;

export type GetStoreFrontControllerHandleQueryResponse =
  GetStoreFrontControllerHandle200;

export type GetStoreFrontControllerHandleQuery = {
  Response: GetStoreFrontControllerHandle200;
  QueryParams: GetStoreFrontControllerHandleQueryParams;
  Errors:
    | GetStoreFrontControllerHandle400
    | GetStoreFrontControllerHandle401
    | GetStoreFrontControllerHandle404
    | GetStoreFrontControllerHandle409
    | GetStoreFrontControllerHandle500;
};
