/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { GetSimilarProductsResponseDto } from "./GetSimilarProductsResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export type GetSimilarProductsControllerHandlePathParams = {
  /**
   * @description ID of the product to find similar products for
   * @type string
   */
  productId: string;
};

export type GetSimilarProductsControllerHandleQueryParams = {
  /**
   * @description Maximum number of similar products to return
   * @minLength 1
   * @maxLength 50
   * @default 10
   * @type number | undefined
   */
  limit?: number;
  /**
   * @description Page number for pagination
   * @minLength 1
   * @default 1
   * @type number | undefined
   */
  page?: number;
};

/**
 * @description Returns similar products
 */
export type GetSimilarProductsControllerHandle200 =
  GetSimilarProductsResponseDto;

/**
 * @description Bad Request
 */
export type GetSimilarProductsControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type GetSimilarProductsControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Product not found
 */
export type GetSimilarProductsControllerHandle404 = any;

/**
 * @description Conflict
 */
export type GetSimilarProductsControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type GetSimilarProductsControllerHandle500 = InternalServerErrorDto;

export type GetSimilarProductsControllerHandleQueryResponse =
  GetSimilarProductsControllerHandle200;

export type GetSimilarProductsControllerHandleQuery = {
  Response: GetSimilarProductsControllerHandle200;
  PathParams: GetSimilarProductsControllerHandlePathParams;
  QueryParams: GetSimilarProductsControllerHandleQueryParams;
  Errors:
    | GetSimilarProductsControllerHandle400
    | GetSimilarProductsControllerHandle401
    | GetSimilarProductsControllerHandle404
    | GetSimilarProductsControllerHandle409
    | GetSimilarProductsControllerHandle500;
};
