/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const storeFrontThemeEnum3 = {
  DEFAULT: "DEFAULT",
  AMETHYST_HAZE: "AMETHYST_HAZE",
  SOLAR_DUSK: "SOLAR_DUSK",
} as const;

export type StoreFrontThemeEnum3 =
  (typeof storeFrontThemeEnum3)[keyof typeof storeFrontThemeEnum3];

export type GetStoreFrontResponseDto = {
  /**
   * @type object
   */
  storeFront: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    organizationId: string;
    /**
     * @type string
     */
    logoImage: string;
    /**
     * @type string
     */
    bannerImage: string;
    /**
     * @type string
     */
    location: string;
    /**
     * @type string
     */
    theme: StoreFrontThemeEnum3;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};
