/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetUserCouponsByCouponIdResponseDto } from "./GetUserCouponsByCouponIdResponseDto.ts";

export type GetUserCouponsByCouponIdControllerHandlePathParams = {
  /**
   * @type string
   */
  couponId: string;
};

/**
 * @description User coupons retrieved successfully
 */
export type GetUserCouponsByCouponIdControllerHandle200 =
  GetUserCouponsByCouponIdResponseDto;

export type GetUserCouponsByCouponIdControllerHandleQueryResponse =
  GetUserCouponsByCouponIdControllerHandle200;

export type GetUserCouponsByCouponIdControllerHandleQuery = {
  Response: GetUserCouponsByCouponIdControllerHandle200;
  PathParams: GetUserCouponsByCouponIdControllerHandlePathParams;
  Errors: any;
};
