/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetUserCouponResponseDto = {
  /**
   * @type object
   */
  userCoupon: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    couponId: string;
    /**
     * @type string
     */
    userId: string;
  };
};
