/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetUserCouponsByCouponsIdsResponseDto } from "./GetUserCouponsByCouponsIdsResponseDto.ts";

export type GetUserCouponsByCouponsIdsControllerHandleQueryParams = {
  /**
   * @description Array of coupon IDs
   * @type array
   */
  couponIds: string[];
};

/**
 * @description User coupons retrieved successfully
 */
export type GetUserCouponsByCouponsIdsControllerHandle200 =
  GetUserCouponsByCouponsIdsResponseDto;

export type GetUserCouponsByCouponsIdsControllerHandleQueryResponse =
  GetUserCouponsByCouponsIdsControllerHandle200;

export type GetUserCouponsByCouponsIdsControllerHandleQuery = {
  Response: GetUserCouponsByCouponsIdsControllerHandle200;
  QueryParams: GetUserCouponsByCouponsIdsControllerHandleQueryParams;
  Errors: any;
};
