/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetUserCouponsByCouponsIdsResponseDto = {
  /**
   * @type array
   */
  userCoupons: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    couponId: string;
    /**
     * @type string
     */
    userId: string;
  }[];
};
