/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { GetUserCouponResponseDto } from "./GetUserCouponResponseDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export type GetUserCouponControllerHandlePathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description User coupon retrieved successfully
 */
export type GetUserCouponControllerHandle200 = GetUserCouponResponseDto;

/**
 * @description Bad Request
 */
export type GetUserCouponControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type GetUserCouponControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type GetUserCouponControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type GetUserCouponControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type GetUserCouponControllerHandle500 = InternalServerErrorDto;

export type GetUserCouponControllerHandleQueryResponse =
  GetUserCouponControllerHandle200;

export type GetUserCouponControllerHandleQuery = {
  Response: GetUserCouponControllerHandle200;
  PathParams: GetUserCouponControllerHandlePathParams;
  Errors:
    | GetUserCouponControllerHandle400
    | GetUserCouponControllerHandle401
    | GetUserCouponControllerHandle404
    | GetUserCouponControllerHandle409
    | GetUserCouponControllerHandle500;
};
