/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type NotFoundErrorDto = {
  /**
   * @type number
   */
  statusCode: number;
  /**
   * @type string
   */
  message: string;
};
