/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { SearchProductResponseDto } from "./SearchProductResponseDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export const searchProductControllerHandleQueryParamsOrderDirectionEnum = {
  asc: "asc",
  desc: "desc",
} as const;

export type SearchProductControllerHandleQueryParamsOrderDirectionEnum =
  (typeof searchProductControllerHandleQueryParamsOrderDirectionEnum)[keyof typeof searchProductControllerHandleQueryParamsOrderDirectionEnum];

export const searchProductControllerHandleQueryParamsOrderByEnum = {
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  title: "title",
  price: "price",
} as const;

export type SearchProductControllerHandleQueryParamsOrderByEnum =
  (typeof searchProductControllerHandleQueryParamsOrderByEnum)[keyof typeof searchProductControllerHandleQueryParamsOrderByEnum];

export type SearchProductControllerHandleQueryParams = {
  /**
   * @minLength 1
   * @default 1
   * @type number | undefined
   */
  page?: number;
  /**
   * @minLength 1
   * @maxLength 100
   * @default 10
   * @type number | undefined
   */
  perPage?: number;
  /**
   * @type string | undefined
   */
  orderDirection?: SearchProductControllerHandleQueryParamsOrderDirectionEnum;
  /**
   * @type string | undefined
   */
  orderBy?: SearchProductControllerHandleQueryParamsOrderByEnum;
  /**
   * @type string | undefined
   */
  searchTerm?: string;
  /**
   * @type string | undefined
   */
  organizationId?: string;
};

/**
 * @description Returns a list of products
 */
export type SearchProductControllerHandle200 = SearchProductResponseDto;

/**
 * @description Bad Request
 */
export type SearchProductControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type SearchProductControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type SearchProductControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type SearchProductControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type SearchProductControllerHandle500 = InternalServerErrorDto;

export type SearchProductControllerHandleQueryResponse =
  SearchProductControllerHandle200;

export type SearchProductControllerHandleQuery = {
  Response: SearchProductControllerHandle200;
  QueryParams: SearchProductControllerHandleQueryParams;
  Errors:
    | SearchProductControllerHandle400
    | SearchProductControllerHandle401
    | SearchProductControllerHandle404
    | SearchProductControllerHandle409
    | SearchProductControllerHandle500;
};
