/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SearchUserResponseDto = {
  /**
   * @type array | undefined
   */
  users?: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    name: string;
    /**
     * @type string
     */
    email: string;
    /**
     * @type boolean
     */
    emailVerified: boolean;
    /**
     * @type boolean | undefined
     */
    banned?: boolean;
    /**
     * @type string
     */
    banExpires?: string | null;
    /**
     * @type string | undefined
     */
    banReason?: string;
    /**
     * @type string | undefined
     */
    image?: string;
    /**
     * @type string | undefined
     */
    role?: string;
    /**
     * @type string
     */
    createdAt?: string | null;
    /**
     * @type string
     */
    updatedAt?: string | null;
  }[];
  /**
   * @type string | undefined
   */
  message?: string;
  /**
   * @type number | undefined
   */
  total?: number;
  /**
   * @type number | undefined
   */
  pages?: number;
};
