/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { SearchPromotionsResponseDto } from "./SearchPromotionsResponseDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export type SearchPromotionsControllerHandleQueryParams = {
  /**
   * @description Filter by product ID
   * @type string | undefined
   */
  productId?: string;
  /**
   * @description Filter by user ID
   * @type string | undefined
   */
  userId?: string;
  /**
   * @description Minimum discount percentage
   * @type string | undefined
   */
  minDiscountPercentage?: string;
  /**
   * @description Maximum discount percentage
   * @type string | undefined
   */
  maxDiscountPercentage?: string;
  /**
   * @description Valid from date (ISO string)
   * @type string | undefined
   */
  validFrom?: string;
  /**
   * @description Valid until date (ISO string)
   * @type string | undefined
   */
  validUntil?: string;
  /**
   * @description Filter by active status
   * @type string | undefined
   */
  isActive?: string;
  /**
   * @description Page number (default: 1)
   * @type string | undefined
   */
  page?: string;
  /**
   * @description Items per page (default: 10)
   * @type string | undefined
   */
  limit?: string;
};

/**
 * @description Promotions retrieved successfully
 */
export type SearchPromotionsControllerHandle200 = SearchPromotionsResponseDto;

/**
 * @description Bad Request
 */
export type SearchPromotionsControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type SearchPromotionsControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type SearchPromotionsControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type SearchPromotionsControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type SearchPromotionsControllerHandle500 = InternalServerErrorDto;

export type SearchPromotionsControllerHandleQueryResponse =
  SearchPromotionsControllerHandle200;

export type SearchPromotionsControllerHandleQuery = {
  Response: SearchPromotionsControllerHandle200;
  QueryParams: SearchPromotionsControllerHandleQueryParams;
  Errors:
    | SearchPromotionsControllerHandle400
    | SearchPromotionsControllerHandle401
    | SearchPromotionsControllerHandle404
    | SearchPromotionsControllerHandle409
    | SearchPromotionsControllerHandle500;
};
