/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SearchProductResponseDto = {
  /**
   * @type array | undefined
   */
  products?: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    description: string;
    /**
     * @type string
     */
    image: string;
    /**
     * @type string
     */
    imageBlur: string;
    /**
     * @type number
     */
    price: number;
    /**
     * @type string
     */
    title: string;
    /**
     * @type string
     */
    organizationId: string;
    /**
     * @type string
     */
    createdAt?: string | null;
    /**
     * @type string
     */
    updatedAt?: string | null;
  }[];
  /**
   * @type string | undefined
   */
  message?: string;
  /**
   * @type number | undefined
   */
  total?: number;
  /**
   * @type number | undefined
   */
  pages?: number;
};
