/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { SearchUserResponseDto } from "./SearchUserResponseDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export const searchUserControllerHandleQueryParamsOrderByEnum = {
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  name: "name",
  email: "email",
} as const;

export type SearchUserControllerHandleQueryParamsOrderByEnum =
  (typeof searchUserControllerHandleQueryParamsOrderByEnum)[keyof typeof searchUserControllerHandleQueryParamsOrderByEnum];

export const searchUserControllerHandleQueryParamsOrderDirectionEnum = {
  asc: "asc",
  desc: "desc",
} as const;

export type SearchUserControllerHandleQueryParamsOrderDirectionEnum =
  (typeof searchUserControllerHandleQueryParamsOrderDirectionEnum)[keyof typeof searchUserControllerHandleQueryParamsOrderDirectionEnum];

export type SearchUserControllerHandleQueryParams = {
  /**
   * @type string | undefined
   */
  searchTerm?: string;
  /**
   * @type string | undefined
   */
  orderBy?: SearchUserControllerHandleQueryParamsOrderByEnum;
  /**
   * @type string | undefined
   */
  orderDirection?: SearchUserControllerHandleQueryParamsOrderDirectionEnum;
  /**
   * @type number | undefined
   */
  perPage?: number;
  /**
   * @type number | undefined
   */
  page?: number;
};

/**
 * @description Returns a list of users
 */
export type SearchUserControllerHandle200 = SearchUserResponseDto;

/**
 * @description Bad Request
 */
export type SearchUserControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type SearchUserControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type SearchUserControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type SearchUserControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type SearchUserControllerHandle500 = InternalServerErrorDto;

export type SearchUserControllerHandleQueryResponse =
  SearchUserControllerHandle200;

export type SearchUserControllerHandleQuery = {
  Response: SearchUserControllerHandle200;
  QueryParams: SearchUserControllerHandleQueryParams;
  Errors:
    | SearchUserControllerHandle400
    | SearchUserControllerHandle401
    | SearchUserControllerHandle404
    | SearchUserControllerHandle409
    | SearchUserControllerHandle500;
};
