/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SearchUserCouponsResponseDto = {
  /**
   * @type array
   */
  userCoupons: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    couponId: string;
    /**
     * @type string
     */
    userId: string;
  }[];
  /**
   * @type number
   */
  total: number;
  /**
   * @type number
   */
  page: number;
  /**
   * @type number
   */
  limit: number;
  /**
   * @type number
   */
  totalPages: number;
};
