/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { SearchUserCouponsResponseDto } from "./SearchUserCouponsResponseDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export type SearchUserCouponsControllerHandleQueryParams = {
  /**
   * @description Filter by coupon ID
   * @type string | undefined
   */
  couponId?: string;
  /**
   * @description Page number (default: 1)
   * @type string | undefined
   */
  page?: string;
  /**
   * @description Items per page (default: 10)
   * @type string | undefined
   */
  limit?: string;
};

/**
 * @description User coupons retrieved successfully
 */
export type SearchUserCouponsControllerHandle200 = SearchUserCouponsResponseDto;

/**
 * @description Bad Request
 */
export type SearchUserCouponsControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type SearchUserCouponsControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type SearchUserCouponsControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type SearchUserCouponsControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type SearchUserCouponsControllerHandle500 = InternalServerErrorDto;

export type SearchUserCouponsControllerHandleQueryResponse =
  SearchUserCouponsControllerHandle200;

export type SearchUserCouponsControllerHandleQuery = {
  Response: SearchUserCouponsControllerHandle200;
  QueryParams: SearchUserCouponsControllerHandleQueryParams;
  Errors:
    | SearchUserCouponsControllerHandle400
    | SearchUserCouponsControllerHandle401
    | SearchUserCouponsControllerHandle404
    | SearchUserCouponsControllerHandle409
    | SearchUserCouponsControllerHandle500;
};
