/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { SearchCouponsResponseDto } from "./SearchCouponsResponseDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";

export type SearchCouponsControllerHandleQueryParams = {
  /**
   * @description Filter by product ID
   * @type string | undefined
   */
  productId?: string;
  /**
   * @description Filter by user ID
   * @type string | undefined
   */
  userId?: string;
  /**
   * @description Minimum discount percentage
   * @type number | undefined
   */
  minDiscountPercentage?: number;
  /**
   * @description Maximum discount percentage
   * @type number | undefined
   */
  maxDiscountPercentage?: number;
  /**
   * @description Minimum quantity
   * @type number | undefined
   */
  minQuantity?: number;
  /**
   * @description Maximum quantity
   * @type number | undefined
   */
  maxQuantity?: number;
  /**
   * @description Page number (default: 1)
   * @type number | undefined
   */
  page?: number;
  /**
   * @description Items per page (default: 10)
   * @type number | undefined
   */
  limit?: number;
};

/**
 * @description Coupons retrieved successfully
 */
export type SearchCouponsControllerHandle200 = SearchCouponsResponseDto;

/**
 * @description Bad Request
 */
export type SearchCouponsControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type SearchCouponsControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type SearchCouponsControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type SearchCouponsControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type SearchCouponsControllerHandle500 = InternalServerErrorDto;

export type SearchCouponsControllerHandleQueryResponse =
  SearchCouponsControllerHandle200;

export type SearchCouponsControllerHandleQuery = {
  Response: SearchCouponsControllerHandle200;
  QueryParams: SearchCouponsControllerHandleQueryParams;
  Errors:
    | SearchCouponsControllerHandle400
    | SearchCouponsControllerHandle401
    | SearchCouponsControllerHandle404
    | SearchCouponsControllerHandle409
    | SearchCouponsControllerHandle500;
};
