/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SearchCouponsResponseDto = {
  /**
   * @type array
   */
  coupons: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type number
     */
    currentQuantity: number;
    /**
     * @type number
     */
    discountPercentage: number;
    /**
     * @type number
     */
    maxQuantity: number;
    /**
     * @type string
     */
    productId: string;
    /**
     * @type string
     */
    userId: string;
    /**
     * @type string
     */
    createdAt?: string | null;
    /**
     * @type string
     */
    updatedAt?: string | null;
  }[];
  /**
   * @type number
   */
  total: number;
  /**
   * @type number
   */
  page: number;
  /**
   * @type number
   */
  limit: number;
  /**
   * @type number
   */
  totalPages: number;
};
