/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";
import type { UpdatePromotionBodyDto } from "./UpdatePromotionBodyDto.ts";
import type { UpdatePromotionResponseDto } from "./UpdatePromotionResponseDto.ts";

export type UpdatePromotionControllerHandlePathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Promotion updated successfully
 */
export type UpdatePromotionControllerHandle200 = UpdatePromotionResponseDto;

/**
 * @description Bad Request
 */
export type UpdatePromotionControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type UpdatePromotionControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type UpdatePromotionControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type UpdatePromotionControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type UpdatePromotionControllerHandle500 = InternalServerErrorDto;

export type UpdatePromotionControllerHandleMutationRequest =
  UpdatePromotionBodyDto;

export type UpdatePromotionControllerHandleMutationResponse =
  UpdatePromotionControllerHandle200;

export type UpdatePromotionControllerHandleMutation = {
  Response: UpdatePromotionControllerHandle200;
  Request: UpdatePromotionControllerHandleMutationRequest;
  PathParams: UpdatePromotionControllerHandlePathParams;
  Errors:
    | UpdatePromotionControllerHandle400
    | UpdatePromotionControllerHandle401
    | UpdatePromotionControllerHandle404
    | UpdatePromotionControllerHandle409
    | UpdatePromotionControllerHandle500;
};
