/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";
import type { UpdateCouponBodyDto } from "./UpdateCouponBodyDto.ts";
import type { UpdateCouponResponseDto } from "./UpdateCouponResponseDto.ts";

export type UpdateCouponControllerHandlePathParams = {
  /**
   * @description Coupon ID
   * @type string
   */
  id: string;
};

/**
 * @description Coupon updated successfully
 */
export type UpdateCouponControllerHandle200 = UpdateCouponResponseDto;

/**
 * @description Bad Request
 */
export type UpdateCouponControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type UpdateCouponControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type UpdateCouponControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type UpdateCouponControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type UpdateCouponControllerHandle500 = InternalServerErrorDto;

export type UpdateCouponControllerHandleMutationRequest = UpdateCouponBodyDto;

export type UpdateCouponControllerHandleMutationResponse =
  UpdateCouponControllerHandle200;

export type UpdateCouponControllerHandleMutation = {
  Response: UpdateCouponControllerHandle200;
  Request: UpdateCouponControllerHandleMutationRequest;
  PathParams: UpdateCouponControllerHandlePathParams;
  Errors:
    | UpdateCouponControllerHandle400
    | UpdateCouponControllerHandle401
    | UpdateCouponControllerHandle404
    | UpdateCouponControllerHandle409
    | UpdateCouponControllerHandle500;
};
