/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const updateStoreFrontBodyDtoThemeEnum = {
  DEFAULT: "DEFAULT",
  AMETHYST_HAZE: "AMETHYST_HAZE",
  SOLAR_DUSK: "SOLAR_DUSK",
} as const;

export type UpdateStoreFrontBodyDtoThemeEnum =
  (typeof updateStoreFrontBodyDtoThemeEnum)[keyof typeof updateStoreFrontBodyDtoThemeEnum];

export type UpdateStoreFrontBodyDto = {
  /**
   * @type string
   */
  organizationId: string;
  /**
   * @type string | undefined
   */
  logoImage?: string;
  /**
   * @type string | undefined
   */
  bannerImage?: string;
  /**
   * @type string | undefined
   */
  location?: string;
  /**
   * @type string | undefined
   */
  theme?: UpdateStoreFrontBodyDtoThemeEnum;
};
