/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdatePromotionBodyDto = {
  /**
   * @minLength 0
   * @maxLength 100
   * @type number | undefined
   */
  discountPercentage?: number;
  /**
   * @type string | undefined, date-time
   */
  validUntil?: string;
};
