/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";
import type { UpdateProductBodyDto } from "./UpdateProductBodyDto.ts";
import type { UpdateProductResponseDto } from "./UpdateProductResponseDto.ts";

export type UpdateProductControllerHandlePathParams = {
  /**
   * @description The ID of the product to update
   * @type string
   */
  productId: string;
};

/**
 * @description Product updated successfully
 */
export type UpdateProductControllerHandle200 = UpdateProductResponseDto;

/**
 * @description Bad Request
 */
export type UpdateProductControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type UpdateProductControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type UpdateProductControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type UpdateProductControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type UpdateProductControllerHandle500 = InternalServerErrorDto;

export type UpdateProductControllerHandleMutationRequest = UpdateProductBodyDto;

export type UpdateProductControllerHandleMutationResponse =
  UpdateProductControllerHandle200;

export type UpdateProductControllerHandleMutation = {
  Response: UpdateProductControllerHandle200;
  Request: UpdateProductControllerHandleMutationRequest;
  PathParams: UpdateProductControllerHandlePathParams;
  Errors:
    | UpdateProductControllerHandle400
    | UpdateProductControllerHandle401
    | UpdateProductControllerHandle404
    | UpdateProductControllerHandle409
    | UpdateProductControllerHandle500;
};
