/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestErrorDto } from "./BadRequestErrorDto.ts";
import type { ConflictErrorDto } from "./ConflictErrorDto.ts";
import type { InternalServerErrorDto } from "./InternalServerErrorDto.ts";
import type { NotFoundErrorDto } from "./NotFoundErrorDto.ts";
import type { UnauthorizedErrorDto } from "./UnauthorizedErrorDto.ts";
import type { UpdateStoreFrontBodyDto } from "./UpdateStoreFrontBodyDto.ts";
import type { UpdateStoreFrontResponseDto } from "./UpdateStoreFrontResponseDto.ts";

/**
 * @description Store front updated successfully
 */
export type UpdateStoreFrontControllerHandle200 = UpdateStoreFrontResponseDto;

/**
 * @description Bad Request
 */
export type UpdateStoreFrontControllerHandle400 = BadRequestErrorDto;

/**
 * @description Unauthorized
 */
export type UpdateStoreFrontControllerHandle401 = UnauthorizedErrorDto;

/**
 * @description Not Found
 */
export type UpdateStoreFrontControllerHandle404 = NotFoundErrorDto;

/**
 * @description Conflict
 */
export type UpdateStoreFrontControllerHandle409 = ConflictErrorDto;

/**
 * @description Internal Server Error
 */
export type UpdateStoreFrontControllerHandle500 = InternalServerErrorDto;

export type UpdateStoreFrontControllerHandleMutationRequest =
  UpdateStoreFrontBodyDto;

export type UpdateStoreFrontControllerHandleMutationResponse =
  UpdateStoreFrontControllerHandle200;

export type UpdateStoreFrontControllerHandleMutation = {
  Response: UpdateStoreFrontControllerHandle200;
  Request: UpdateStoreFrontControllerHandleMutationRequest;
  Errors:
    | UpdateStoreFrontControllerHandle400
    | UpdateStoreFrontControllerHandle401
    | UpdateStoreFrontControllerHandle404
    | UpdateStoreFrontControllerHandle409
    | UpdateStoreFrontControllerHandle500;
};
